### ISSUE TITLE
add expanders for dependent objects

### ISSUE THREAD

**Issue by mfrasca** [Ghini/server#13]
## todo
- [x] add an expander button on each row.
- [x] clicking on it will retrieve the 'depending' objects, 
- [x] do not not show the rows, only the buttons corresponding to the depending collections.
- [x] clicking on the new created buttons will expand/collapse the corresponding block.
- [x] clicking on a button expands ONLY that section, collapsing any other.
:no_entry:  collapsing a section acts recursively, collapsing everything below it. - 

## original text

when you have a row in the results list, like a taxon, or an accession, or a location, there's a whole list of objects associated to it, and actually more than one list:
taxa have dependent taxa, and identified accessions.
accessions have plants (and identifications?).
plants have propagations.
propagations aren't there yet.
locations have plants.

bootstrap has "collapsers", https://www.w3schools.com/bootstrap4/bootstrap_ref_js_collapse.asp, they have very flexible behaviour, we can work with them, recursively.

![image](https://user-images.githubusercontent.com/122869/57532047-8203eb80-7300-11e9-9f18-6414f65b48c0.png)

we need to enhance the answer to `filter_json`, split it depending on the query type, add the option for dependent objects,

**Comment by mfrasca** [comment]
I've been declaring intentions, and have added a very rough start for a query parser.  back to lex+yacc, away from pyparsing, it was a funny thing to learn, but I prefer the real stuff.

**Comment by mfrasca** [comment]
in the meanwhile, we now have a quite complete query parser, similar to ghini.desktop, not part of issue #13, not part of any issue I'm afraid, but I wrote it already.  too bad.  :rofl: 

the server serves the URLs `depending/`.  we need to use that.
I will add an expander button on each row.
clicking on it will retrieve the 'depending' objects, it will not not show the rows, only the buttons corresponding to the depending collections.  it may also be none.  clicking on the new created buttons will expand/collapse the corresponding block.  the corresponding block has the same structure as the root results rows, so the process can continue recursively.
