### ISSUE TITLE
add data insertion modal boxes

### ISSUE THREAD

**Issue by mfrasca** [Ghini/server#16]
## logic
some objects (Contact, Accession, Location, Taxon) can be added without relation to previously inserted data.  they don't need a parent object.  Taxon is a border case, since a Taxon has a 'parent' taxon property, but that's not characterizing the object, it may even change.  Plant and Verification only make sense in combination with an Accession and that's an immutable property.  in fact, the URL to a Plant as well as the URL to a Verification contain their related Accession code.

objects are added, or edited.  the javascript client requests editing forms from the django server.  the django server serves pre-populated forms for specific objects, and empty forms for new objects.  forms are not cached.  forms served by django only contain table rows, while the client holds the rest of the form.  the javascript client adds the POST verb to empty forms, because that's for new objects, and the PUT verb to pre-populated forms, because that's for editing objects.  we use PUT and not PATCH because every time we're rewriting the whole edited object.

### URL logic

let's collect the URL involved in this story.

all URLs are named, after the class, plus an optional suffix.
* list API url, it lets you GET the list, and POST a new object, suffix `-list`; 
* detail API url, meant for individual GET, and PUT, suffix `-detail`;  
* infobox URL, for populating the infobox, suffix `-infobox`;  
* empty form URL, suffix `-post-form`;  
* populated form URL, suffix `-put-form`; 

concrete urls regarding the same object or the same collection can be computed one from the other, like they all share the same prefix, so that the javascript code can juggle with replacing suffixes.

## things to do
- [x] add context menu - drop down
- [x] add main menu
- [x] define Django view for both empty and populated forms content
- [x] systematically use url names
- [x] put more structure in url values
- [x] add target property to forms
- [x] allow for POST/PUT in target and let javascript change it
- [x] populate / clean form before displaying it
- [x] add new objects
- [x] edit existing objects
- [x] add dependent objects (Plant, Verification)
- [x] freeze properties that should not be edited (split into #38)
- [x] do not let user post incomplete request (split into #23)

**Comment by mfrasca** [comment]
forms are computed by django, subclassing `from django.forms import ModelForm`.
form fields are also computed by django + select2.

**Comment by mfrasca** [comment]
the two remaining points moved to individual issues.
