### ISSUE TITLE
let ghini.server handle the geographic client

### ISSUE THREAD

**Issue by mfrasca** [Ghini/server#2]
the geographic client, we already have it as ghini.web, it can serve as an initial step towards ghini.guest. once it's served, we have to tie it to ghini.server.

## todo
- [x] add a `map` page next to results and pictures.  
- [x] make it show the map from osm (Leaflet).  
- [x] set initial view (initially hard coded)
- [x] let institution data define initial view (#83),
- [x] add coordinates to `Plant` model (#79),
- [x] propagate plant coordinates to `Accession` and `Taxon`,
- [x] store search in hash,
- [x] restore search from hash,
- [x] show plants on the map, matching the Results,
- [x] before any row is selected, centre map according to all Results,
- [x] make sure we can associate a single Results row to multiple plant markers,
- [x] show active plant(s) in different colour,
- [x] when row in Results is clicked, Marker is highlighted too,
- [x] if highlighted Marker falls outside map, map is re-centred,
- [x] when plant in Map is clicked, row in Results is highlighted,
- [x] if highlighted Results row falls outside view, view is re-centred,
- [x] report same two-lines in popup,
- [x] disable popup when moving out of map,

## move to own issues:
- [x] when selects area on map, search is updated,
- [x] show icon in centre of marker (initially hard coded),
- [x] add .icon and .layer_zoom fields to `Plant` model,
