### ISSUE TITLE
document the REST interface

### ISSUE THREAD

**Issue by mfrasca** [Ghini/server#6]
the rest interface to our database should offer reading, creating, patching, linking, deleting.
it should follow a logic, and the logic should be documented, and the documentation should match the code, and the code should be under continuous integration testing.

- [x] add documentation initial structure
- [x] register it on readthedocs
- [x] add the development document

then describe what I did, so it makes sense if we need to expand it.
- [x] the main GET, POST, PUT, DELETE structure, 
- [x] the other GET entry points, all derived from the above.
- [x] what about unit testing? see issue #33
- [x] what about deployment? see note in https://github.com/mfrasca/ghini/projects/1
