### ISSUE TITLE
add institution and collection information

### ISSUE THREAD

**Issue by mfrasca** [Ghini/server#83]
add collection meta-data, like the institution name and location, contact people, type of collection, etc.
possibly and maybe:
- [x] add a new reserved table even if it just holds one institution (see also #32).
- [ ] table holds only core data, rest goes in notes (related to #47).
- [ ] stored queries would be notes, too (this is #49).
